sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t ayfantis/eshop -f Dockerfile.dev .

script:
  - docker run -e CI=true ayfantis/eshop npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "eshop"
  env: "Eshop-env"
  bucket_name: "elasticbeanstalk-us-east-1-583762202529"
  bucket_path: "eshop"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"